[package]
name          = "amq-protocol-types"
version       = "5.1.0" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - types"
repository    = "https://github.com/CleverCloud/amq-protocol"
documentation = "https://docs.rs/amq-protocol-types"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_types"

[features]
verbose-errors = []

[dependencies]
cookie-factory = "^0.3"
serde_json     = "^1.0"

[dependencies.nom]
version  = "^5.0"
git = "git://github.com/Geal/nom"
features = ["std"]

[dependencies.serde]
version  = "^1.0"
features = ["derive"]

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
