[package]
name          = "amq-protocol-codegen"
version       = "0.27.0"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - codegen"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol-codegen"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_codegen"

[dependencies]
handlebars   = "^1.0.0-beta.2"
serde        = "^1.0"
serde_derive = "^1.0"
serde_json   = "^1.0"

[dependencies.amq-protocol-types]
version = "^1.0"
path    = "../types"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
