[package]
name          = "amq-protocol"
version       = "2.0.0-beta3" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol"
keywords      = ["amqp","rabbitmq","protocol","nom"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"
build         = "build.rs"

[lib]
name = "amq_protocol"

[build-dependencies]
serde_json = "^1.0"

[build-dependencies.amq-protocol-codegen]
version = "=2.0.0-beta3"
path    = "../codegen"

[dependencies]
cookie-factory = "^0.2.4"
nom            = "=5.0.0-beta1"
url            = "^1.7"

[dependencies.amq-protocol-codegen]
version = "=2.0.0-beta3"
path    = "../codegen"

[dependencies.amq-protocol-types]
version = "=2.0.0-beta3"
path    = "../types"

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
